packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - '@nestjs/core'
  - 'unrs-resolver'
